---
test:
  azure_stack_defaults: &azure_stack_defaults
    host: azurestackhost
    tenant: AZURE_STACK_TENANT
    subscription: AZURE_STACK_SUBSCRIPTION
    userid: AZURE_STACK_USERID
    password: AZURE_STACK_PASSWORD
  azure_stack:
    <<: *azure_stack_defaults
